#!/bin/bash

# Retrieve arguments
domain=$1
path=$2
user=$3
is_public=$4

parent_dir=/var/www/webapp_$user
if [ $path = "\\" ]
then
    final_path=$parent_dir
    name="root_webapp"
else
    final_path=$parent_dir$path
    name=$(echo $2 | cut -d '/' -f 2)
fi

netftp_path=/ftp_webapp_$user

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a my_webapp
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

sudo yunohost app setting my_webapp name -v $name

# Check user
sudo yunohost user list --json | grep -q "\"username\": \"$user\""
if [[ ! $? -eq 0 ]]; then
echo "Wrong user"
    exit 1
fi
sudo yunohost app setting my_webapp ftp_user -v $user

# Créer le dossier parent des webapp pour l'utilisateur
if test ! -d $parent_dir
then	# Créer le dossier parent uniquement si il n'existe pas
    sudo mkdir $parent_dir

    # Set permissions
    sudo chmod 775 -R $parent_dir
    sudo chown -hR www-data:www-data $parent_dir
else
    echo "Création du dossier $parent_dir ignorée, le dossier existe déjà."
fi

# Change user ID in configurations
sed -i "s@FTPUSER@$user@g" ../sources/index_ftp.html
sed -i "s@HOST@$domain@g" ../sources/index_ftp.html
sed -i "s@NET2FTP@$netftp_path@g" ../sources/index_ftp.html

# Copy files to the right place
sudo mkdir $final_path
sudo cp ../sources/index.html $final_path/
# Vérifie si pure-ftpd est déjà installé
if test -f /usr/sbin/pure-ftpd-ldap
then	# Si oui, vérifie si net2ftp est également installé.
    if test -d $parent_dir/netftp
    then
	sudo cp ../sources/index_ftp.html $final_path/index.html	# Remplace l'index.html par celui intégrant les informations ftp
    fi
fi

# Set permissions
sudo chmod 775 -R $final_path
sudo chown -hR $user:www-data $final_path

# Modify Nginx configuration file and copy it to Nginx conf directory
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@ALIASTOCHANGE@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$name.conf

# Make app public if necessary
sudo yunohost app setting my_webapp is_public -v "$is_public"
if [ "$is_public" = "Yes" ];
then
    sudo yunohost app setting my_webapp skipped_uris -v "/"
fi

# Reload Nginx and regenerate SSOwat conf
sudo service nginx reload
sudo yunohost app ssowatconf
